## Exemplary ML workflow

The following shows an exemplary Airflow DAG by building a MNIST Image Classification Workflow with Keras and the Taskflow API. The DAG automates the process of training and testing a convolutional neural network (CNN) model using the popular MNIST dataset and Keras. The DAG demonstrates how to set up a simple task flow for data preprocessing, model training, and model testing. A python file of the DAG can be found [here](https://github.com/seblum/mlops-engineering-book/tree/master/manuscript/files/05-Airflow/08_exemlary-ML-Workflow)

The Airflow DAG is named `"tutorial_mnist_keras_taskflow_api"` and is designed to be informative and easy to understand. It includes three distinct tasks: `preprocess_data()`, `train_model(data_paths_dict)`, and `test_model(model_name)`. These tasks collectively create a streamlined workflow for building, training, and evaluating a deep learning model.

The `preprocess_data()` task preprocesses the MNIST dataset, which includes loading and scaling the image data and converting class labels into categorical format. The preprocessed data is then saved as NumPy arrays for subsequent use. This task returns a dictionary containing file paths to these preprocessed data arrays.

The `train_model(data_paths_dict)` task is responsible for building and training the Keras CNN model. It starts by loading the preprocessed data using the data paths provided in the input dictionary. The CNN architecture comprises convolutional and pooling layers, followed by flattening and dense layers. After model compilation, training begins with specified hyperparameters such as batch size and epochs. Once training is complete, the model is saved with a name, and the task returns this name as output.

The `test_model(model_name)` task loads the trained Keras model using the provided model name and evaluates its performance on the test dataset. It calculates and prints both the test loss and accuracy, providing insights into how well the model generalizes to unseen data.

The DAG execution flow is straightforward. It starts with the `preprocess_data()` task, which prepares the data for model training. The output of this task is then passed as an input to the `train_model(data_paths_dict)` task, where the CNN model is constructed and trained. Finally, the `test_model(model_name)` task tests the trained model and reports its performance metrics.

\footnotesize
```python
# build dag that includes everything from before
def to_be_done():
    pass
```
\normalsize

