### Monitoring

Incorporated into the setup is a monitoring system leveraging Prometheus and Grafana. While not a direct component of the ML pipeline, this configuration serves as an instructive illustration of proficient cluster monitoring. It encompasses a fundamental monitoring setup accomplished through the utilization of Prometheus and Grafana.

Prometheus and Grafana play distinct yet complementary roles in the domain of monitoring and observability. Prometheus is primarily responsible for collecting, storing, and alerting based on time-series metrics. It scrapes data from various sources, defines alerting rules, and supports service discovery, making it a robust monitoring and alerting tool. It also offers a query language for metric analysis and flexible data retention policies.

On the other hand, Grafana specializes in data visualization and interactive dashboard creation. It connects to data sources like Prometheus and transforms metric data into visually engaging charts and graphs. Grafana is instrumental in designing comprehensive monitoring dashboards, visualizing alerts, and facilitating data exploration. Together, Prometheus and Grafana form a powerful monitoring stack, enabling organizations to monitor, analyze, and visualize their systems effectively.

Both tools, Prometheus and Grafana, are seamlessly deployed via a Helm chart. The crucial interconnection between Grafana and Prometheus is thoughtfully established within the Grafana Helm chart, ensuring a cohesive and comprehensive monitoring solution.

#### Prometheus

The provided Terraform code facilitates the deployment of Prometheus and Prometheus Operator Custom Resource Definitions (CRDs) for the ML platform dashboard. This deployment leverages Helm for efficient management, allowing for customizable configurations and streamlined monitoring and alerting system setup.

The process begins with the definition of a Helm release named `"prometheus"` responsible for deploying Prometheus, a comprehensive monitoring and alerting toolkit, to the specified Kubernetes namespace. The Helm chart utilized for this deployment is sourced from the Prometheus community Helm charts repository, adhering to a specified version.

Within the `"values"` block, you'll find a YAML-encoded configuration for Prometheus. This configuration tailors specific aspects of the Prometheus installation, including the option to disable Alertmanager and Prometheus Pushgateway components. It also provides the flexibility to enable or disable persistent volumes for the Prometheus server.

\footnotesize
```javascript
resource "helm_release" "prometheus" {
  chart            = "prometheus"
  name             = "prometheus"
  namespace        = var.namespace
  create_namespace = var.create_namespace

  repository = "https://prometheus-community.github.io/helm-charts"
  version    = "19.7.2"

  values = [
    yamlencode({
      alertmanager = {
        enabled = false
      }
      prometheus-pushgateway = {
        enabled = false
      }
      server = {
        persistentVolume = {
          enabled = false
        }
      }
    })
  ]
}
```
\normalsize

In addition to the Prometheus release, another Helm release named `"prometheus-operator-crds"` is established. This release is focused on deploying the Custom Resource Definitions (CRDs) essential for the Prometheus Operator. Similarly, the Helm chart used for this deployment originates from the Prometheus community Helm charts repository but at a distinct version.

The Prometheus Operator CRDs are essential for defining and managing Prometheus instances and associated resources within the Kubernetes cluster, ensuring effective monitoring and alerting for the ML platform dashboard.

\footnotesize
```javascript
resource "helm_release" "prometheus-operator-crds" {
  chart            = "prometheus-operator-crds"
  name             = "prometheus-operator-crds"
  namespace        = var.namespace
  create_namespace = var.create_namespace

  repository = "https://prometheus-community.github.io/helm-charts"
  version    = "5.1.0"
}
```
\normalsize

#### Grafana

The provided Terraform code deploys Grafana, a dashboard and visualization platform, for an ML platform. The Grafana deployment is highly customized, with various settings and configurations.

A Helm release named `"grafana"` is defined, deploying Grafana to the specified Kubernetes namespace. It pulls the Grafana chart from the official Helm charts repository at version `"6.57.4."` The `"values"` block contains a YAML-encoded configuration for Grafana, including various settings related to service type, Ingress, data sources, dashboard providers, and more.

- **Service and Ingress Configuration**: The Grafana service is configured to be of type `"ClusterIP"` and an Ingress resource is enabled for external access. Several annotations are added to the Ingress to customize how it interacts with the Kubernetes cluster, including specifying the hostname, scheme, healthcheck path, and other settings. The Ingress is set up to handle requests for the specified domain name and subdomain, allowing external access to Grafana.
- **Data Sources Configuration**: The configuration includes data source settings, specifically for Prometheus. It defines a data source named "Prometheus" with details like the type, URL, access mode, and setting it as the default data source. This configuration allows Grafana to retrieve metrics and data from Prometheus for visualization and dashboard creation.
- **Dashboard Providers Configuration**: Grafana's dashboard providers are configured using a YAML block. It defines a default provider with options specifying the path to dashboards. This configuration enables Grafana to load dashboards from the specified path within the Grafana container.
- **Dashboards Configuration**: The code defines a set of dashboards and their configurations. Each dashboard is associated with a data source (in this case, Prometheus) and has various settings such as gnetId (unique identifier), revision, and data source. These configurations determine which data is displayed on each dashboard and how it is accessed.
- **Grafana Configuration (grafana.ini)**: This section provides a set of configurations for Grafana itself, including security settings that allow embedding Grafana in iframes. It specifies the server's domain and root URL, enabling Grafana to serve from a subpath. Additionally, GitHub authentication is enabled for user sign-up and authentication, using the provided GitHub OAuth client ID and secret.

\footnotesize
```javascript
resource "helm_release" "grafana" {
  chart            = "grafana"
  name             = "grafana"
  namespace        = var.namespace
  create_namespace = var.create_namespace

  repository = "https://grafana.github.io/helm-charts/"
  version    = "6.57.4"

  values = [
    yamlencode({
      service = {
        enabled = true
        type    = "ClusterIP"
      }
      ingress = {
        enabled = true
        annotations = {
          "external-dns.alpha.kubernetes.io/hostname"  = "${var.domain_name}",
          "alb.ingress.kubernetes.io/scheme"           = "internet-facing",
          "alb.ingress.kubernetes.io/target-type"      = "ip",
          "kubernetes.io/ingress.class"                = "alb",
          "alb.ingress.kubernetes.io/group.name"       = "mlplatform",
          "alb.ingress.kubernetes.io/healthcheck-path" = "/api/health"
        }
        labels   = {}
        path     = "${var.domain_suffix}"
        pathType = "Prefix"
        hosts = [
          "${var.domain_name}",
          "www.${var.domain_name}"
        ]
      },
      datasources = {
        "datasources.yaml" = {
          apiVersion = 1
          datasources = [
            {
              name      = "Prometheus"
              type      = "prometheus"
              url       = "http://prometheus-server.${var.namespace}.svc.cluster.local"
              access    = "proxy"
              isDefault = true
            }
          ]
        }
      },
      dashboardProviders = {
        "dashboardproviders.yaml" = {
          apiVersion = 1
          providers = [
            {
              name   = "'default'"
              orgId  = 1
              folder = "''"
              type : "file"
              disableDeletion : false
              editable : true
              options = {
                path = "/var/lib/grafana/dashboards/default"
              }
            }
          ]
        }
      }
      dashboards = {
        default = {
          prometheus-stats = {
            gnetId     = 2
            revision   = 2
            datasource = "Prometheus"
          }
          prometheus-stats-2 = {
            gnetId     = 315
            datasource = "Prometheus"
          }
          k8s-cluster = {
            gnetId     = 6417
            datasource = "Prometheus"
          }
        }
      }
      "grafana.ini" = {
        security = {
          allow_embedding = true # enables iframe loading
        },
        server = {
          domain : "${var.domain_name}"
          root_url : "%(protocol)s://%(domain)s/grafana/"
          serve_from_sub_path : true
          # https://grafana.com/docs/grafana/latest/auth/github/#enable-github-in-grafana
        },
        "auth.github" = {
          enabled       = true
          allow_sign_up = true
          scopes        = "user:email,read:org"
          auth_url      = "https://github.com/login/oauth/authorize"
          token_url     = "https://github.com/login/oauth/access_token"
          api_url       = "https://api.github.com/user"
          # team_ids: grafana-user-team
          # allowed_organizations:
          client_id     = var.git_client_id
          client_secret = var.git_client_secret
        }
      }
  })]
}
```
\normalsize


